// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version=6
indicator('Day Of Week Price Distribution [LuxAlgo]', 'LuxAlgo - DoW Distribution', overlay = false, max_labels_count = 500)
//---------------------------------------------------------------------------------------------------------------------}
//CONSTANTS & STRINGS & INPUTS
//---------------------------------------------------------------------------------------------------------------------{
GREEN                   = #089981
RED                     = #F23645
SILVER                  = #B2B5BE 
SILVER_80               = color.new(SILVER,80)
DATA                    = #DBDBDB
HEADERS                 = #808080
BACKGROUND              = #161616
BORDERS                 = #2E2E2E

TOP_RIGHT               = 'Top Right'
BOTTOM_RIGHT            = 'Bottom Right'
BOTTOM_LEFT             = 'Bottom Left'

TINY                    = 'Tiny'
SMALL                   = 'Small'
NORMAL                  = 'Normal'
LARGE                   = 'Large'
HUGE                    = 'Huge'

DASHBOARD_GROUP         = 'Dashboard'
STYLE_GROUP             = 'Style'

EM_SPACE                = ' '
EN_SPACE                = ' '
FOUR_PER_EM_SPACE       = ' '

iqrColorTag             = 'IQR Area'+FOUR_PER_EM_SPACE+FOUR_PER_EM_SPACE
medianColorTag          = 'Median'+EM_SPACE+FOUR_PER_EM_SPACE

dashboardTooltip        = 'Enable or disable the dashboard.'
dashboardPositionTooltip= 'Select the dashboard location.'
dashboardSizeTooltip    = 'Select the dashboard size.'

limitInput              = input.int(    10,         'Window')
offsetInput             = input.int(    20,         'Spacing')

dashboardInput          = input.bool(   true,       'Dashboard',    group = DASHBOARD_GROUP, tooltip = dashboardTooltip)
dashboardPositionInput  = input.string( TOP_RIGHT,  'Position',     group = DASHBOARD_GROUP, tooltip = dashboardPositionTooltip , options = [TOP_RIGHT,BOTTOM_RIGHT,BOTTOM_LEFT])
dashboardSizeInput      = input.string( SMALL,      'Size',         group = DASHBOARD_GROUP, tooltip = dashboardSizeTooltip,      options = [TINY,SMALL,NORMAL,LARGE,HUGE])

bullishColorInput       = input.color(  GREEN,      'Bullish',      group = STYLE_GROUP)
bearishColorInput       = input.color(  RED,        'Bearish',      group = STYLE_GROUP)
iqrColorInput           = input.color(  SILVER_80,  iqrColorTag,    group = STYLE_GROUP, inline = 'iqr')
iqrAutoInput            = input.bool(   true,       'Auto',         group = STYLE_GROUP, inline = 'iqr')
medianColorInput        = input.color(  SILVER,     medianColorTag, group = STYLE_GROUP, inline = 'median')
medianAutoInput         = input.bool(   true,       'Auto',         group = STYLE_GROUP, inline = 'median')

//---------------------------------------------------------------------------------------------------------------------}
//DATA STRUCTURES & VARIABLES
//---------------------------------------------------------------------------------------------------------------------{
type daydata
    array<float> prices = na
    array<float> delta  = na
    array<float> volume = na
    array<bool>  isup   = na
    array<int>   unix   = na
    string       day    = na

type display
    array<label> point_lbl
    array<label> day_lbl
    array<box> qboxes
    array<line> medians

type rowData
    string date = ''
    string data = ''

type dashboardData
    rowData bullishPrice
    rowData bearishPrice
    rowData bullishDelta
    rowData bearishDelta
    rowData largerVolume
    rowData smallerVolume

var array<daydata> weekholder = syminfo.type == 'crypto' ? array.from(
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Sunday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Monday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Tuesday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Wednesday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Thursday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Friday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Saturday')
    ) : array.from(
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Monday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Tuesday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Wednesday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Thursday'),
     daydata.new(array.new<float>(),array.new<float>(),array.new<float>(),array.new<bool>(),array.new<int>(),'Friday')
    )
     
var display panel           = display.new(array.new<label>(),array.new<label>(),array.new<box>(),array.new<line>())
var dashboardData dashboard = dashboardData.new(rowData.new(),rowData.new(),rowData.new(),rowData.new(),rowData.new(),rowData.new())
int n                       = bar_index
var string timeformat       = "yyyy-MM-dd"
var string timeformatDow    = 'EEE (yyyy-MM-dd)'

var parsedDashboardPosition = switch dashboardPositionInput
    TOP_RIGHT       => position.top_right
    BOTTOM_RIGHT    => position.bottom_right
    BOTTOM_LEFT     => position.bottom_left

var parsedDashboardSize     = switch dashboardSizeInput
    TINY            => size.tiny
    SMALL           => size.small
    NORMAL          => size.normal
    LARGE           => size.large
    HUGE            => size.huge

if barstate.isfirst
    for i = 0 to limitInput * weekholder.size() - 1
        array.push(panel.point_lbl, label.new(na, na, '•'
          , color = #00000000
          , style = label.style_label_center ))

    for i = 0 to weekholder.size() - 1
        array.push(panel.day_lbl, label.new(na, na
          , style = label.style_label_up
          , color = #00000000
          , textcolor = chart.fg_color))
        
        array.push(panel.qboxes, box.new(na, na, na , na
          , border_color = na
          , bgcolor = iqrAutoInput ? color.new(chart.fg_color,80) : iqrColorInput))

        array.push(panel.medians, line.new(na, na, na, na
          , color = medianAutoInput ? chart.fg_color : medianColorInput
          , width = 2))

//---------------------------------------------------------------------------------------------------------------------}
//USER-DEFINED FUNCTIONS
//---------------------------------------------------------------------------------------------------------------------{
gatherData() =>
    dow = dayofweek(time_tradingday)

    if dow != dow[1]
        dayholder = array.get(weekholder, dow[1] - 1)
        dayholder.prices.push(close[1])
        dayholder.delta.push(close[1] - open[1])
        dayholder.volume.push(volume[1])
        dayholder.isup.push(close[1] > open[1])
        dayholder.unix.push(syminfo.type == 'crypto' ? time[1] : time_close[1])

        if array.size(dayholder.prices) > limitInput
            dayholder.prices.shift()
            dayholder.delta.shift()
            dayholder.volume.shift()
            dayholder.isup.shift()
            dayholder.unix.shift()

displayData() =>
    if barstate.islast
        i           = -offsetInput * (weekholder.size() - 1)
        idx         = 0
        float min   = na

        //Loop trough main array
        for [index1, data] in weekholder
            //Set point
            for [index2, value] in data.prices                
                get_lbl     = array.get(panel.point_lbl, idx)
                string tag  = str.format('Price: {0}\nChange: {1}\nVolume: {2}\n{3}',
                     str.tostring(value,format.mintick),
                     str.tostring(data.delta.get(index2),format.mintick),
                     na(data.volume.get(index2)) ? 'NaN' : str.tostring(data.volume.get(index2),format.volume),
                     str.format_time(data.unix.get(index2), timeformat, syminfo.timezone))                
                label.set_xy(get_lbl, n + i, value)
                label.set_textcolor(get_lbl, array.get(data.isup, index2) ? bullishColorInput : bearishColorInput)
                get_lbl.set_tooltip(tag)
                idx += 1

            //Set Quartiles
            q75 = array.percentile_linear_interpolation(data.prices, 75)
            q25 = array.percentile_linear_interpolation(data.prices, 25)
            
            qbox = array.get(panel.qboxes, index1)
            box.set_lefttop(qbox, n + i - offsetInput / 10, q75)
            box.set_rightbottom(qbox, n + i + offsetInput / 10, q25)
            
            //Set Median
            med = array.median(data.prices)

            median = array.get(panel.medians, index1)
            line.set_xy1(median, n + i - offsetInput / 10, med)
            line.set_xy2(median, n + i + offsetInput / 10, med)

            if not na(array.min(data.prices)) and array.size(data.prices) > 2
                min := na(min) ? array.min(data.prices) : math.min(array.min(data.prices), min)

            i += offsetInput
        
        //Set x labels
        i := -offsetInput * (weekholder.size() - 1)
        for [index, data] in weekholder
            get_lbl = array.get(panel.day_lbl, index)

            label.set_xy(get_lbl, n + i, min)
            label.set_text(get_lbl, data.day)

            i += offsetInput

cell(table t_able, int column, int row, string data, color = #FFFFFF, align = text.align_right, color background = na, float height = 0) => t_able.cell(column,row,data,text_color = color, text_size = parsedDashboardSize, text_halign = align, bgcolor = background, height = height)

divider(table t_able, int row) =>    
    string rowDivider = '━━━━━━━━━━━━━━━━━━━━━━'
    t_able.merge_cells(0,row,2,row)
    cell(t_able,0,row,rowDivider,align = text.align_center, height = 0.5, color = BORDERS)

displayDashboard() =>
    var table t_able    = table.new(parsedDashboardPosition,3,13    
     , bgcolor          = BACKGROUND    
     , border_width     = 0    
     , frame_color      = BORDERS
     , frame_width      = 1
     , force_overlay    = false)

    if dashboardInput
        if barstate.islast
            float bullishPrice  = weekholder.first().prices.max()
            float bearishPrice  = weekholder.first().prices.min()
            float bullishDelta  = weekholder.first().delta.max()
            float bearishDelta  = weekholder.first().delta.min()
            float largerVolume  = weekholder.first().volume.max()
            float smallerVolume = weekholder.first().volume.min()

            for [index, eachDay] in weekholder
                for [innerIndex, eachPrice] in eachDay.prices
                    int date = eachDay.unix.get(innerIndex)

                    if eachPrice >= bullishPrice
                        bullishPrice := eachPrice
                        dashboard.bullishPrice.data := str.tostring(eachPrice,format.mintick)
                        dashboard.bullishPrice.date := str.format_time(date, timeformatDow, syminfo.timezone)

                    if eachPrice <= bearishPrice
                        bearishPrice := eachPrice
                        dashboard.bearishPrice.data := str.tostring(eachPrice,format.mintick)
                        dashboard.bearishPrice.date := str.format_time(date, timeformatDow, syminfo.timezone)
                    
                    float delta = eachDay.delta.get(innerIndex)
                    if delta >= bullishDelta
                        bullishDelta := delta
                        dashboard.bullishDelta.data := str.tostring(delta,format.mintick)
                        dashboard.bullishDelta.date := str.format_time(date, timeformatDow, syminfo.timezone)

                    if delta <= bearishDelta
                        bearishDelta := delta
                        dashboard.bearishDelta.data := str.tostring(delta,format.mintick)
                        dashboard.bearishDelta.date := str.format_time(date, timeformatDow, syminfo.timezone)

                    float eachVolume = eachDay.volume.get(innerIndex)
                    if eachVolume >= largerVolume
                        largerVolume := eachVolume
                        dashboard.largerVolume.data := str.tostring(eachVolume,format.volume)
                        dashboard.largerVolume.date := str.format_time(date, timeformatDow, syminfo.timezone)

                    if eachVolume <= smallerVolume
                        smallerVolume := eachVolume
                        dashboard.smallerVolume.data := str.tostring(eachVolume,format.volume)
                        dashboard.smallerVolume.date := str.format_time(date, timeformatDow, syminfo.timezone)

            t_able.merge_cells(0,0,2,0)
            cell(t_able,0,0,str.format('DoW Core Metrics ({0} weeks)',limitInput),align = text.align_center, color = DATA)

            divider(t_able,1)                        
            divider(t_able,3)
            divider(t_able,5)
            divider(t_able,7)
            divider(t_able,9)
            divider(t_able,11)

            cell(t_able,0,2,    'Highest Price',        align = text.align_left, color = HEADERS)            
            cell(t_able,0,4,    'Lowest Price',         align = text.align_left, color = HEADERS)            
            cell(t_able,0,6,    'Most Bullish Delta',   align = text.align_left, color = HEADERS)                        
            cell(t_able,0,8,    'Most Bearish Delta',   align = text.align_left, color = HEADERS)                        
            cell(t_able,0,10,   'Larger Volume',        align = text.align_left, color = HEADERS)            
            cell(t_able,0,12,   'Smaller Volume',       align = text.align_left, color = HEADERS)

            cell(t_able,1,2,    dashboard.bullishPrice.date,    color = DATA)
            cell(t_able,2,2,    dashboard.bullishPrice.data,    color = DATA)
            cell(t_able,1,4,    dashboard.bearishPrice.date,    color = DATA)
            cell(t_able,2,4,    dashboard.bearishPrice.data,    color = DATA)
            cell(t_able,1,6,    dashboard.bullishDelta.date,    color = DATA)
            cell(t_able,2,6,    dashboard.bullishDelta.data,    color = bullishColorInput)
            cell(t_able,1,8,    dashboard.bearishDelta.date,    color = DATA)
            cell(t_able,2,8,    dashboard.bearishDelta.data,    color = bearishColorInput)
            cell(t_able,1,10,   dashboard.largerVolume.date,    color = DATA)
            cell(t_able,2,10,   dashboard.largerVolume.data,    color = DATA)
            cell(t_able,1,12,   dashboard.smallerVolume.date,   color = DATA)
            cell(t_able,2,12,   dashboard.smallerVolume.data,   color = DATA)

//---------------------------------------------------------------------------------------------------------------------}
//MUTABLE VARIABLES & EXECUTION
//---------------------------------------------------------------------------------------------------------------------{
gatherData()

displayData()

displayDashboard()

//---------------------------------------------------------------------------------------------------------------------}