// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version=6
indicator("Structure & Trend Dashboard", "Structure MTF Dashboard", overlay = true, max_boxes_count = 500, max_lines_count = 500, max_labels_count = 500)

//---------------------------------------------------------------------------------------------------------------------}
// Constants
//---------------------------------------------------------------------------------------------------------------------{
DATA                    = #DBDBDB
HEADERS                 = #808080
BACKGROUND              = #161616
BORDERS                 = #2E2E2E

//---------------------------------------------------------------------------------------------------------------------}
// Types
//---------------------------------------------------------------------------------------------------------------------{
type FVG
    box bx
    bool is_bull
    float top
    float bot

//---------------------------------------------------------------------------------------------------------------------}
// Inputs
//---------------------------------------------------------------------------------------------------------------------{
grp_smc     = "Market Structure"
show_smc    = input.bool(true, "Show Market Structure", group = grp_smc)
smc_tf      = input.timeframe("", "Structure Timeframe", group = grp_smc, tooltip = "Calculates Key Levels from this timeframe, breaks occur on chart timeframe.")
swing_len   = input.int(5, "Swing Length", group = grp_smc)
show_candles= input.bool(true, "Color Candles Based on Trend", group = grp_smc)

grp_liq     = "Liquidity Sweeps"
show_liq    = input.bool(true, "Show Liquidity Sweeps", group = grp_liq)
liq_tf      = input.timeframe("", "Liquidity Timeframe", group = grp_liq, tooltip = "Timeframe for detecting key liquidity levels to be swept.")

grp_fvg     = "Fair Value Gaps"
show_fvg    = input.bool(true, "Show Fair Value Gaps", group = grp_fvg)
fvg_limit   = input.int(5, "Max Active FVGs", minval = 1, group = grp_fvg, tooltip = "Limits the number of active FVGs so they don't extend indefinitely.")

DASHBOARD_GROUP         = 'Dashboard'
dashboardInput          = input.bool(true, 'Enable Dashboard', group = DASHBOARD_GROUP, tooltip = 'Enable or disable the trend dashboard.')
dashboardPositionInput  = input.string('Top Right', 'Position', group = DASHBOARD_GROUP, options = ['Top Right','Bottom Right','Bottom Left'])
dashboardSizeInput      = input.string('Small', 'Size', group = DASHBOARD_GROUP, options = ['Tiny','Small','Normal','Large','Huge'])

//---------------------------------------------------------------------------------------------------------------------}
// Variables
//---------------------------------------------------------------------------------------------------------------------{
var parsedDashboardPosition = switch dashboardPositionInput
    'Top Right'       => position.top_right
    'Bottom Right'    => position.bottom_right
    'Bottom Left'     => position.bottom_left

var parsedDashboardSize     = switch dashboardSizeInput
    'Tiny'            => size.tiny
    'Small'           => size.small
    'Normal'          => size.normal
    'Large'           => size.large
    'Huge'            => size.huge

var fvg_arr = array.new<FVG>()

// Structure variables
var float active_ph = na
var int active_ph_t = na
var float active_pl = na
var int active_pl_t = na

var line ph_line = na
var line pl_line = na

var int chart_trend = 1

// Liquidity variables
var float liq_ph = na
var int liq_ph_t = na
var float liq_pl = na
var int liq_pl_t = na

var line liq_ph_line_glow = na
var line liq_ph_line = na
var line liq_pl_line_glow = na
var line liq_pl_line = na

//---------------------------------------------------------------------------------------------------------------------}
// Functions
//---------------------------------------------------------------------------------------------------------------------{
f_get_trend(len) =>
    ph = ta.pivothigh(high, len, len)
    pl = ta.pivotlow(low, len, len)
    var float last_ph = na
    var float last_pl = na
    if not na(ph)
        last_ph := ph
    if not na(pl)
        last_pl := pl
    var int tr = 1
    if close > last_ph
        tr := 1
    else if close < last_pl
        tr := -1
    tr

f_get_pivots(len) =>
    ph = ta.pivothigh(high, len, len)
    pl = ta.pivotlow(low, len, len)
    var float p_h = na
    var int p_h_t = na
    var float p_l = na
    var int p_l_t = na
    if not na(ph)
        p_h := ph
        p_h_t := time[len]
    if not na(pl)
        p_l := pl
        p_l_t := time[len]
    [p_h, p_h_t, p_l, p_l_t]

cell(table t_able, int column, int row, string data, color text_col = #FFFFFF, string align = text.align_center, color background = na, float height = 0) => 
    t_able.cell(column, row, data, text_color = text_col, text_size = parsedDashboardSize, text_halign = align, bgcolor = background, height = height)

divider(table t_able, int row, int lastColumn) =>    
    string rowDivider = '━━━━━━━━━━━━━━━━━━━━━━'
    t_able.merge_cells(0, row, lastColumn, row)
    cell(t_able, 0, row, rowDivider, text_col = BORDERS, align = text.align_center, height = 0.5)

//---------------------------------------------------------------------------------------------------------------------}
// Data Requests
//---------------------------------------------------------------------------------------------------------------------{
trend_D   = request.security(syminfo.tickerid, "1D", f_get_trend(swing_len))
trend_H4  = request.security(syminfo.tickerid, "240", f_get_trend(swing_len))
trend_H1  = request.security(syminfo.tickerid, "60", f_get_trend(swing_len))
trend_M15 = request.security(syminfo.tickerid, "15", f_get_trend(swing_len))
trend_M5  = request.security(syminfo.tickerid, "5", f_get_trend(swing_len))
trend_M1  = request.security(syminfo.tickerid, "1", f_get_trend(swing_len))

[h_ph, h_ph_t, h_pl, h_pl_t] = request.security(syminfo.tickerid, smc_tf == "" ? timeframe.period : smc_tf, f_get_pivots(swing_len))
[l_ph, l_ph_t, l_pl, l_pl_t] = request.security(syminfo.tickerid, liq_tf == "" ? timeframe.period : liq_tf, f_get_pivots(swing_len))

//---------------------------------------------------------------------------------------------------------------------}
// Main Logic & Visuals
//---------------------------------------------------------------------------------------------------------------------{
// Market Structure
if show_smc
    if not na(h_ph) and (na(active_ph_t) or h_ph_t != active_ph_t)
        active_ph := h_ph
        active_ph_t := h_ph_t
        ph_line := line.new(active_ph_t, active_ph, time, active_ph, xloc.bar_time, color = color.new(#f23645, 50), style = line.style_dashed)
    
    if not na(h_pl) and (na(active_pl_t) or h_pl_t != active_pl_t)
        active_pl := h_pl
        active_pl_t := h_pl_t
        pl_line := line.new(active_pl_t, active_pl, time, active_pl, xloc.bar_time, color = color.new(#089981, 50), style = line.style_dashed)
        
    if not na(ph_line)
        line.set_x2(ph_line, time)
    if not na(pl_line)
        line.set_x2(pl_line, time)
        
    if not na(active_ph) and close > active_ph
        bool is_bos = (chart_trend == 1)
        chart_trend := 1
        line.set_x2(ph_line, time)
        line.set_color(ph_line, #089981)
        line.set_style(ph_line, line.style_solid)
        
        lbl_text = is_bos ? "BOS" : "CHoCH"
        label.new(math.round(math.avg(line.get_x1(ph_line), time)), active_ph, lbl_text, xloc.bar_time, textcolor = #089981, style = label.style_label_down, color = #00000000, size = size.tiny)
        
        active_ph := na
        ph_line := na
        
    if not na(active_pl) and close < active_pl
        bool is_bos = (chart_trend == -1)
        chart_trend := -1
        line.set_x2(pl_line, time)
        line.set_color(pl_line, #f23645)
        line.set_style(pl_line, line.style_solid)
        
        lbl_text = is_bos ? "BOS" : "CHoCH"
        label.new(math.round(math.avg(line.get_x1(pl_line), time)), active_pl, lbl_text, xloc.bar_time, textcolor = #f23645, style = label.style_label_up, color = #00000000, size = size.tiny)
        
        active_pl := na
        pl_line := na

// Liquidity Sweeps
if show_liq
    if not na(l_ph) and (na(liq_ph_t) or l_ph_t != liq_ph_t)
        liq_ph := l_ph
        liq_ph_t := l_ph_t
        line.delete(liq_ph_line_glow)
        line.delete(liq_ph_line)
        liq_ph_line_glow := line.new(liq_ph_t, liq_ph, time, liq_ph, xloc.bar_time, color=color.new(#f23645, 80), width=6)
        liq_ph_line := line.new(liq_ph_t, liq_ph, time, liq_ph, xloc.bar_time, color=color.new(#f23645, 0), width=2, style = line.style_dashed)
    
    if not na(l_pl) and (na(liq_pl_t) or l_pl_t != liq_pl_t)
        liq_pl := l_pl
        liq_pl_t := l_pl_t
        line.delete(liq_pl_line_glow)
        line.delete(liq_pl_line)
        liq_pl_line_glow := line.new(liq_pl_t, liq_pl, time, liq_pl, xloc.bar_time, color=color.new(#089981, 80), width=6)
        liq_pl_line := line.new(liq_pl_t, liq_pl, time, liq_pl, xloc.bar_time, color=color.new(#089981, 0), width=2, style = line.style_dashed)

    if not na(liq_ph_line)
        line.set_x2(liq_ph_line_glow, time)
        line.set_x2(liq_ph_line, time)
    if not na(liq_pl_line)
        line.set_x2(liq_pl_line_glow, time)
        line.set_x2(liq_pl_line, time)

    if not na(liq_ph) and high > liq_ph
        if close < liq_ph // Swept
            label.new(time, high, "×", xloc.bar_time, textcolor = #f23645, style = label.style_none, size = size.normal)
            line.set_style(liq_ph_line, line.style_solid)
        else // Broken completely
            line.delete(liq_ph_line_glow)
            line.delete(liq_ph_line)
            
        liq_ph := na
        liq_ph_line := na
        liq_ph_line_glow := na

    if not na(liq_pl) and low < liq_pl
        if close > liq_pl // Swept
            label.new(time, low, "×", xloc.bar_time, textcolor = #089981, style = label.style_none, size = size.normal)
            line.set_style(liq_pl_line, line.style_solid)
        else // Broken completely
            line.delete(liq_pl_line_glow)
            line.delete(liq_pl_line)
            
        liq_pl := na
        liq_pl_line := na
        liq_pl_line_glow := na

// Fair Value Gaps
if show_fvg
    if not na(high[2]) and not na(low[2])
        if low > high[2] and close[1] > high[2]
            b = box.new(time[2], low, time, high[2], xloc = xloc.bar_time, bgcolor = color.new(#089981, 80), border_color = color.new(#089981, 100))
            array.push(fvg_arr, FVG.new(b, true, low, high[2]))
            
        if high < low[2] and close[1] < low[2]
            b = box.new(time[2], low[2], time, high, xloc = xloc.bar_time, bgcolor = color.new(#f23645, 80), border_color = color.new(#f23645, 100))
            array.push(fvg_arr, FVG.new(b, false, low[2], high))
            
    if array.size(fvg_arr) > 0
        for i = array.size(fvg_arr) - 1 to 0
            f = array.get(fvg_arr, i)
            box.set_right(f.bx, time)
            
            if f.is_bull and low < f.bot
                box.delete(f.bx)
                array.remove(fvg_arr, i)
            else if not f.is_bull and high > f.top
                box.delete(f.bx)
                array.remove(fvg_arr, i)
                
    while array.size(fvg_arr) > fvg_limit
        f = array.shift(fvg_arr)
        box.delete(f.bx)

barcolor(show_candles ? (chart_trend == 1 ? #089981 : #f23645) : na)

//---------------------------------------------------------------------------------------------------------------------}
// Dashboard Render
//---------------------------------------------------------------------------------------------------------------------{
var table t_able = dashboardInput ? table.new(parsedDashboardPosition, 3, 11, bgcolor = BACKGROUND, border_width = 0, frame_color = BORDERS, frame_width = 1, force_overlay = false) : na

if dashboardInput and barstate.islast
    t_able.merge_cells(0, 0, 2, 0)
    cell(t_able, 0, 0, 'Trend Alignment', text_col = DATA, align = text.align_center)
    
    divider(t_able, 1, 2)
    
    cell(t_able, 0, 2, 'HTF', text_col = HEADERS)
    cell(t_able, 1, 2, 'LTF', text_col = HEADERS)
    cell(t_able, 2, 2, 'Aligned', text_col = HEADERS)
    
    divider(t_able, 3, 2)
    
    cell(t_able, 0, 4, '1D (' + (trend_D == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_D == 1 ? #089981 : #f23645))
    cell(t_able, 1, 4, '1H (' + (trend_H1 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_H1 == 1 ? #089981 : #f23645))
    cell(t_able, 2, 4, trend_D == trend_H1 ? '☑' : '☐', text_col = (trend_D == trend_H1 ? #089981 : HEADERS))
    
    divider(t_able, 5, 2)
    
    cell(t_able, 0, 6, '4H (' + (trend_H4 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_H4 == 1 ? #089981 : #f23645))
    cell(t_able, 1, 6, 'M15 (' + (trend_M15 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_M15 == 1 ? #089981 : #f23645))
    cell(t_able, 2, 6, trend_H4 == trend_M15 ? '☑' : '☐', text_col = (trend_H4 == trend_M15 ? #089981 : HEADERS))
    
    divider(t_able, 7, 2)
    
    cell(t_able, 0, 8, '1H (' + (trend_H1 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_H1 == 1 ? #089981 : #f23645))
    cell(t_able, 1, 8, 'M5 (' + (trend_M5 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_M5 == 1 ? #089981 : #f23645))
    cell(t_able, 2, 8, trend_H1 == trend_M5 ? '☑' : '☐', text_col = (trend_H1 == trend_M5 ? #089981 : HEADERS))
    
    divider(t_able, 9, 2)
    
    cell(t_able, 0, 10, 'M15 (' + (trend_M15 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_M15 == 1 ? #089981 : #f23645))
    cell(t_able, 1, 10, 'M1 (' + (trend_M1 == 1 ? 'Bull' : 'Bear') + ')', text_col = (trend_M1 == 1 ? #089981 : #f23645))
    cell(t_able, 2, 10, trend_M15 == trend_M1 ? '☑' : '☐', text_col = (trend_M15 == trend_M1 ? #089981 : HEADERS))

//---------------------------------------------------------------------------------------------------------------------}
